### ISSUE TITLE
Error on require on react-native 0.16.0-rc

### ISSUE THREAD

**Issue by eddiefletchernz** [ideacreation/react-native-barcodescanner#3]
I've just upgraded react-native to 0.16.0-rc and now the barcode scanner is throwing an error on require:

'BarcodeScannerView' has no propType for native prop 'RNBarcodeScannerView.renderToHardwareTextureAndroid' of native type 'boolean'.

**Comment by aeperea** [comment]
+1

**Comment by northfoxz** [comment]
fixed it by replacing the last part of BarcodeScanner.js to

``` javascript
BarcodeScannerView.propTypes = {
  viewFinderBackgroundColor: PropTypes.string,
  viewFinderBorderColor: PropTypes.string,
  viewFinderBorderWidth: PropTypes.number,
  viewFinderBorderLength: PropTypes.number,
  viewFinderDrawLaser: PropTypes.bool,
  viewFinderLaserColor: PropTypes.string,
  torchMode: PropTypes.string,
  cameraType: PropTypes.string,
  onBarCodeRead: PropTypes.func,
  rotation: PropTypes.number,
  scaleX: PropTypes.number,
  scaleY: PropTypes.number,
  translateX: PropTypes.number,
  translateY: PropTypes.number,
  importantForAccessibility: PropTypes.string,
  accessibilityLabel: PropTypes.string,
  testID: PropTypes.string,
  renderToHardwareTextureAndroid: PropTypes.string,
  onLayout: PropTypes.bool
};

var RNBarcodeScannerView = requireNativeComponent('RNBarcodeScannerView', BarcodeScannerView, {
  nativeOnly: {
    onChange: true,
    accessibilityLiveRegion: 'none',
    accessibilityComponentType: 'button'
  }
});
```

**Comment by eddiefletchernz** [comment]
@NorthFoxz Thank you so much! Also I can confirm that this bug is still present with the latest 0.16.0

**Comment by bastengao** [comment]
Same error on react-native  0.17.0

**Comment by bastengao** [comment]
@NorthFoxz Your code works, thanks. :+1:

**Comment by DaleLJefferson** [comment]
I can confirm that @NorthFoxz solution fixes the issue on React Native 0.17 it would be great to get this fixed in master.

**Comment by andreaskeller** [comment]
With @cpunions's merged [pull request](https://github.com/ideacreation/react-native-barcodescanner/pull/5) the issue should now be fixed.
